services:
  backend:
    image: eyapa/eyegazeheatmap:backend_v1
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend/data:/app/data
      - ./backend/db:/app/db

  frontend:
    image: pull eyapa/eyegazeheatmap:frontend_v1
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro