services:
  backend:
    build: ./backend
    # You can name the container so it's always 'backend' for Nginx
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db:/app/db
      - ./backend/data/heatmap_storage:/app/data/heatmap_storage
      - ./backend/data/logs:/app/data/logs
      - ./backend/data/models:/app/data/models
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=sqlite:///./db/database.db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro